project/server/models.py
# project/server/models.py


import datetime

from flask import current_app
from sqlalchemy.orm import backref

from project.server import db, bcrypt
from project.server.user import admin_user_token


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)

    email = db.Column(db.String(255), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    loyalty_card = db.Column(db.Boolean, default=False)

    cart_id = db.Column(db.Integer, db.ForeignKey('carts.id'), nullable=True)
    cart = db.relationship('Cart', backref=backref("user", uselist=False), uselist=False, lazy='joined')

    def __init__(self, email, password, admin=False):
        self.email = email
        self.password = bcrypt.generate_password_hash(
            password, current_app.config.get('BCRYPT_LOG_ROUNDS')
        ).decode('utf-8')
        self.registered_on = datetime.datetime.now()
        self.admin = admin

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def get_token(self):
        # Hardcoded token
        return admin_user_token

    def __repr__(self):
        return '<User {0}>'.format(self.email)


class CartItem(db.Model):
    __tablename__ = 'cart_items'

    # Constants
    ADD = 'add'
    SUBTRACT = 'subtract'
    REMOVE = 'remove'
    ACTIONS = (ADD, SUBTRACT, REMOVE)

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)

    quantity = db.Column(db.Integer, default=1)
    price = db.Column(db.Numeric(asdecimal=True, precision=10, scale=2), nullable=False)

    cart_id = db.Column(db.Integer, db.ForeignKey('carts.id'), nullable=True)
    cart = db.relationship('Cart', backref=backref("cart_items", lazy='joined', cascade="all, delete-orphan"),
                           lazy=True)
    product_id = db.Column(db.Integer, db.ForeignKey('products.id'), nullable=True)
    product = db.relationship('Product', backref="cartitem", uselist=False, lazy='joined')


class Product(db.Model):
    __tablename__ = 'products'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)

    title = db.Column(db.String(255), nullable=False)
    price = db.Column(db.Numeric(asdecimal=True, precision=10, scale=2), nullable=False)
    bogof = db.Column(db.Boolean, default=False)


class Cart(db.Model):
    __tablename__ = 'carts'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)

    total = db.Column(db.Numeric(asdecimal=True, precision=10, scale=2), default=0)

project/server/user/forms.py
# project/server/user/forms.py


from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo


class LoginForm(FlaskForm):
    email = StringField('Email Address', [DataRequired(), Email()])
    password = PasswordField('Password', [DataRequired()])


class RegisterForm(FlaskForm):
    email = StringField(
        'Email Address',
        validators=[
            DataRequired(),
            Email(message=None),
            Length(min=6, max=40)
        ]
    )
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Confirm password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

project/__init__.py
# project/__init__.py

project/server/__init__.py
# project/server/__init__.py


import os

from flask import Flask, render_template
from flask_api import FlaskAPI
from flask_babel import Babel
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_debugtoolbar import DebugToolbarExtension
from flask_bootstrap import Bootstrap
from flask_marshmallow import Marshmallow
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


# instantiate the extensions
login_manager = LoginManager()
bcrypt = Bcrypt()
toolbar = DebugToolbarExtension()
bootstrap = Bootstrap()
db = SQLAlchemy()
migrate = Migrate()
ma = Marshmallow()
babel = Babel()

def create_app(script_info=None):

    # instantiate the app
    app = FlaskAPI(
        __name__,
        template_folder='../client/templates',
        static_folder='../client/static'
    )

    # set config
    app_settings = os.getenv(
        'APP_SETTINGS', 'project.server.config.DevelopmentConfig')
    app.config.from_object(app_settings)
    # set up extensions
    login_manager.init_app(app)
    bcrypt.init_app(app)
    toolbar.init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    ma.init_app(app)
    babel.init_app(app)

    # register blueprints
    from project.server.main.views import main_blueprint
    from project.server.user.views import user_blueprint
    from project.server.main.api import api_blueprint

    app.register_blueprint(user_blueprint)
    app.register_blueprint(main_blueprint)
    app.register_blueprint(api_blueprint)

    # flask login
    from project.server.models import User
    login_manager.login_view = 'user.login'
    login_manager.login_message_category = 'danger'

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.filter(User.id == int(user_id)).first()

    # error handlers
    @app.errorhandler(401)
    def unauthorized_page(error):
        return render_template('errors/401.html'), 401

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template('errors/403.html'), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('errors/404.html'), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template('errors/500.html'), 500

    # shell context for flask cli
    @app.shell_context_processor
    def ctx():
        return {'app': app, 'db': db}

    return app

project/server/main/__init__.py
# project/server/main/__init__.py
from .handlers import *

project/server/main/views.py
# project/server/main/views.py

from flask import render_template, request, g, Blueprint

from project.server.models import Product

main_blueprint = Blueprint('main', __name__)


@main_blueprint.route('/')
def home():
    data = {
        'products': Product.query.all()
    }
    return render_template('main/home.html', **data)

project/server/user/__init__.py
# project/server/user/__init__.py
admin_user_token = 'admin_auth_token'

project/server/user/views.py
# project/server/user/views.py


from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask_login import login_user, logout_user, login_required

from project.server import bcrypt, db
from project.server.models import User
from project.server.user.forms import LoginForm, RegisterForm


user_blueprint = Blueprint('user', __name__,)


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()

        login_user(user)

        flash('Thank you for registering.', 'success')
        return redirect(url_for("main.home"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/members')
@login_required
def members():
    return render_template('user/members.html')

project/client/templates/_base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{{ config.APP_NAME }}{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
</head>

<body>

{% include 'header.html' %}

<div class="site-content">
    <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <br>
                <div class="row">
                    <div class="col-md-12">
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        {% endwith %}

        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
            <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

    </div>
</div>

<br><br>

{% include 'footer.html' %}

<!-- scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{{ url_for('static', filename='main.js') }}" type="text/javascript"></script>
{% block js %}{% endblock %}

</body>
</html>

project/client/templates/footer.html
<footer>
</footer>

project/client/templates/header.html
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <!-- Navbar Brand -->
    <a class="navbar-brand" href="{{ url_for('main.home') }}">{{ config.APP_NAME }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Main Navigation -->
      <ul class="navbar-nav">
      </ul>
      <!-- Login/Logout -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          {% if current_user.is_authenticated %}
          <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
          {% else %}
          <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>

project/client/templates/main/home.html
{% extends "_base.html" %}
{% block content %}
    <div style="display: flex;">
        <div style="width: 60%;">
            <h1>Products</h1>

            {% if not current_user.is_authenticated %}
                <p style="color: red;">Please log in to be able to add products to cart</p>
            {% endif %}
            <hr>
            <br>

            <div style="display: flex;">
                {% for product in products %}
                    <div style="margin: 10px; border: 1px solid #000; padding: 5px;">
                        <p>{{ product.title }}<br> £<span style="font-weight: bold;">{{ product.price }}</span></p>
                        <p>Bogoff: {% if product.bogof %}YES{% else %}NO{% endif %}</p>
                        <button class="js-add-to-cart" data-id="{{ product.id }}">Buy</button>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div style="width: 38%; margin-left: 2%;">
            <h2 style="font-weight: bold;">Cart</h2>
            <div class="cart">
            </div>
            <h3>Total: £<span class="total">0</span></h3>
            {% if current_user.id %}
                <button class="js-toggle-card">Loyalty card: <span class="crd">{{ current_user.loyalty_card }}</span>
            {% endif %}
            </button>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        function updateCart() {
            $.get("{{ url_for('api.get_cart') }}", (data) => {
                $('.cart').html('');
                $.each(data.cart_items, (i, item) => {
                    let product = item.product;
                    let html = $(`
                                <p class="cart-item">
                                    ${product.title} |
                                    <button class="minus">-</button>
                                    <span class="qty">${item.quantity}</span>
                                    <button class="plus">+</button>
                                    | Price:
                                    <span class="price">${item.price}</span>
                                    <button class="remove">X</button>
                                </p>
                            `);
                    html.data('item', item);
                    $('.cart').append(html);
                });
                $('.total').html(data.total);

            })
        }

        $(() => {
            updateCart();
            $('.js-add-to-cart').on('click', (e) => {
                let btn = $(e.target),
                    pr_id = btn.data('id');
                $.ajax({
                    url: "{{ url_for('api.add_to_cart') }}",
                    type: "POST",
                    data: JSON.stringify({'product': pr_id}),
                    contentType: "application/json",
                    statusCode: {
                        400: function (response) {
                            console.log(response);
                        }
                    }
                }).done((result) => {
                    updateCart();
                });
            });
            $('body').on('click', '.minus, .plus', (e) => {
                let $target = $(e.target),
                    itemEl = $target.parent(),
                    item = itemEl.data('item');
                if ($target.hasClass('plus')) {
                    item.quantity += 1;
                }
                else {
                    item.quantity -= 1;
                }
                let jqXHR = $.ajax(
                    {
                        url: `/api/cart_item/${item.id}/`,
                        method: 'PUT',
                        data: JSON.stringify(item),
                        contentType: 'application/json'
                    }
                )
                    .done((res) => {
                        updateCart()
                    })
                    .fail((e) => {
                        console.log(e)
                    })
            });
            $('body').on('click', '.remove', (e) => {
                let $target = $(e.target),
                    itemEl = $target.parent(),
                    item = itemEl.data('item');
                $.ajax({
                    url: `/api/cart_item/${item.id}/`,
                    method: 'DELETE'
                })
                    .done((result) => {
                        updateCart();
                    })
                    .fail((result) => {
                        console.log(result)
                    })

            })
            $('.js-toggle-card').on('click', (e) => {
                let jqXHR = $.ajax(
                    {
                        url: `/api/user/{{ current_user.id }}/`,
                        method: 'PATCH',
                        data: {},
                        contentType: 'application/json'
                    }
                )
                    .done((res) => {
                        updateCart();
                        $('.crd').text(res.card)
                    })
                    .fail((e) => {
                        console.log(e)
                    })
            });
        });
    </script>
{% endblock %}

project/client/templates/user/login.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

  <header class="content-header">
    <h1>Login</h1>
    <hr><br>
  </header>

  <br>

  <form class="form" role="form" method="post" action="">
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    <div class="col-lg-4 col-sm-4">
      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}

      <button class="btn btn-success" type="submit">Sign In!</button>
      <br><br>
      <p>Need to <a href="{{ url_for('user.register') }}">Register</a>?</p>
    </div>
  </form>

{% endblock %}

project/client/templates/user/register.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

  <header class="content-header">
    <h1>Register</h1>
    <hr><br>
  </header>

  <br>

  <form class="form" role="form" method="post" action="">
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    <div class="col-lg-4 col-sm-4">
      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}
      {{ wtf.form_field(form.confirm) }}

      <button class="btn btn-success" type="submit">Register!</button>
      <br><br>
      <p>Already have an account? <a href="{{ url_for('user.login') }}">Sign in</a>.</p>
    </div>
  </form>

{% endblock %}